// Otomatik üretildi: features/banks/banks.ts ve features/services/services.ts kodu→ad eşlemesi.
// Edge function'lar uygulama kodunu içe aktaramadığı için kopyadır; liste değişince yeniden üretilmeli.
export const BANK_NAMES: Record<string, string> = {
  "akbank": "Akbank",
  "aktif-yatirim-bankasi": "Aktif Yatırım Bankası",
  "albaraka-turk-katilim-bankasi": "Albaraka Türk Katılım Bankası",
  "alternatif-bank": "Alternatif Bank",
  "anadolubank": "Anadolubank",
  "arap-turk-bankasi": "Arap Türk Bankası",
  "aytemiz-bank": "Aytemiz Bank",
  "bank-mellat": "Bank Mellat",
  "bank-of-china-turkey": "Bank of China Turkey",
  "bankpozitif-kredi-ve-kalkinma-bankasi": "BankPozitif Kredi ve Kalkınma Bankası",
  "birlesik-fon-bankasi": "Birleşik Fon Bankası",
  "burgan-bank": "Burgan Bank",
  "citibank": "Citibank",
  "colendi-bank": "Colendi Bank",
  "d-yatirim-bankasi": "D Yatırım Bankası",
  "denizbank": "DenizBank",
  "destek-yatirim-bankasi": "Destek Yatırım Bankası",
  "deutsche-bank": "Deutsche Bank",
  "diler-yatirim-bankasi": "Diler Yatırım Bankası",
  "dunya-katilim-bankasi": "Dünya Katılım Bankası",
  "enpara-bank": "Enpara Bank",
  "fibabanka": "Fibabanka",
  "fups-bank": "FUPS Bank",
  "golden-global-yatirim-bankasi": "Golden Global Bank",
  "gsd-yatirim-bankasi": "GSD Yatırım Bankası",
  "habib-bank-limited": "Habib Bank Limited",
  "hayat-finans-katilim-bankasi": "Hayat Finans Katılım Bankası",
  "hedef-yatirim-bankasi": "Hedef Yatırım Bankası",
  "hsbc-bank": "HSBC Bank",
  "icbc-turkey-bank": "ICBC Turkey Bank",
  "iktisat-katilim-bankasi": "İktisat Katılım Bankası",
  "iller-bankasi": "İller Bankası",
  "ing-bank": "ING Bank",
  "intesa-sanpaolo": "Intesa Sanpaolo",
  "istanbul-takas-ve-saklama-bankasi": "Takasbank",
  "jpmorgan-chase-bank": "JPMorgan Chase Bank",
  "kuveyt-turk-katilim-bankasi": "Kuveyt Türk Katılım Bankası",
  "merrill-lynch-yatirim-bank": "Bank of America Yatırım Bank",
  "misyon-yatirim-bankasi": "Misyon Yatırım Bankası",
  "mufg-bank-turkey": "MUFG Bank Turkey",
  "nurol-yatirim-bankasi": "Nurol Yatırım Bankası",
  "odeabank": "Odeabank",
  "pasha-yatirim-bankasi": "PASHA Bank",
  "q-yatirim-bankasi": "Q Yatırım Bankası",
  "qnb-finansbank": "QNB",
  "rabobank": "Hepsi Bank",
  "sekerbank": "Şekerbank",
  "societe-generale": "Société Générale",
  "standard-chartered-yatirim-bankasi-turk": "Standard Chartered Yatırım Bankası Türk",
  "tera-yatirim-bankasi": "Tera Yatırım Bankası",
  "tom-katilim-bankasi": "T.O.M. Katılım Bankası",
  "turk-eximbank": "Türk Eximbank",
  "turk-ticaret-bankasi": "Türk Ticaret Bankası",
  "turkish-bank": "Turkish Bank",
  "turkiye-ekonomi-bankasi": "TEB",
  "turkiye-emlak-katilim-bankasi": "Türkiye Emlak Katılım Bankası",
  "turkiye-finans-katilim-bankasi": "Türkiye Finans Katılım Bankası",
  "turkiye-garanti-bankasi": "Garanti BBVA",
  "turkiye-halk-bankasi": "Halkbank",
  "turkiye-is-bankasi": "Türkiye İş Bankası",
  "turkiye-kalkinma-ve-yatirim-bankasi": "Türkiye Kalkınma ve Yatırım Bankası",
  "turkiye-sinai-kalkinma-bankasi": "TSKB",
  "turkland-bank": "Turkland Bank",
  "vakif-katilim-bankasi": "Vakıf Katılım Bankası",
  "vakifbank": "VakıfBank",
  "yapi-kredi-bankasi": "Yapı Kredi Bankası",
  "ziraat-bankasi": "Ziraat Bankası",
  "ziraat-dinamik-banka": "Ziraat Dinamik Banka",
  "ziraat-katilim-bankasi": "Ziraat Katılım Bankası"
};

export const SERVICE_NAMES: Record<string, string> = {
  "netflix": "Netflix",
  "youtube": "YouTube Premium",
  "youtubemusic": "YouTube Music",
  "spotify": "Spotify",
  "applemusic": "Apple Music",
  "appletv": "Apple TV+",
  "icloud": "iCloud+",
  "hbomax": "HBO Max",
  "mubi": "MUBI",
  "tidal": "TIDAL",
  "deezer": "Deezer",
  "soundcloud": "SoundCloud",
  "claude": "Claude Pro",
  "googlegemini": "Google Gemini Advanced",
  "perplexity": "Perplexity",
  "githubcopilot": "GitHub Copilot",
  "github": "GitHub",
  "googledrive": "Google Drive",
  "dropbox": "Dropbox",
  "notion": "Notion",
  "playstation": "PlayStation Plus",
  "steam": "Steam",
  "discord": "Discord Nitro",
  "telegram": "Telegram Premium",
  "audible": "Audible",
  "duolingo": "Duolingo",
  "coursera": "Coursera",
  "figma": "Figma",
  "vimeo": "Vimeo",
  "twitch": "Twitch",
  "x": "X Premium",
  "vercel": "Vercel"
};
